Repository milvus-io/milvus-proto, pull requests merged in 2022-05, with the labels that each got.

#13 Update proto to the latest version
  proto/common.proto
  proto/milvus.proto
Labels: needs-dco, size/M, do-not-merge/missing-related-issue

#15 Update proto for bulkload minor change
  proto/common.proto
  proto/milvus.proto
Labels: needs-dco, size/M, do-not-merge/missing-related-issue

#19 [skip e2e] Update OWNERS file
  OWNERS
Labels: dco-passed, lgtm, size/S

#18 Update proto files
  proto/common.proto
  proto/milvus.proto
Labels: dco-passed, do-not-merge/hold, approved, size/M

#21 Add node_ids field for QuerySegmentInfo
  proto/milvus.proto
Labels: dco-passed, lgtm, approved, kind/improvement, size/XS

#23 Add test for milvus-proto
  .github/mergify.yml
  .github/workflows/check.yaml
Labels: dco-passed, size/M
