Repository milvus-io/milvus-proto, pull requests merged in 2022-08, with the labels that each got.

#28 Update the proto files for the rbac function
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#31 Add consistency_level field to proto
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#33 Modify response of DescribeCollection and add DescribePartition
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#34 Sync proto from milvus: add GetStatisticsRequest experimental interface
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/M
