Repository milvus-io/milvus-proto, pull requests merged in 2022-10, with the labels that each got.

#42 Add `GetLoadingProgress` rpc and Update `DescribeIndexResponse`
  .gitignore
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/M, kind/improvement

#43 Add GetComponentStates interface
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#45 Use underscores to separate parameter names in the GetLoadingProgressRequest
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#47 Add the generated pb.go files and related tools
  .gitignore
  Makefile
  cmake/CMakeLists.txt
  cmake/protobuf/CMakeLists.txt
  go-api/commonpb/common.pb.go
  go-api/go.mod
  go-api/hook/hook.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/milvus.proto
  proto/schema.proto
  scripts/check_protoc_version.sh
  scripts/core_build.sh
  scripts/proto_gen_go.sh
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#48 Add the `GetVersion` rpc
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
  scripts/core_build.sh
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#50 Add status for GetVersionResponse and CheckHealthResponse
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#51 Use built-in protoc to generate the pb file
  Makefile
  cmake/CMakeLists.txt
  cmake/protobuf/CMakeLists.txt
  scripts/check_protoc_version.sh
  scripts/core_build.sh
  scripts/proto_gen_go.sh
Labels: ci-passed, dco-passed, lgtm, approved, size/M, kind/improvement
