Repository milvus-io/milvus-proto, pull requests merged in 2022-12, with the labels that each got.

#56 add csharp_namespace option
  proto/common.proto
  proto/milvus.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#58 Add compaction plan count field to ManualCompactionResponse
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#60 Add compaction plan count field to ManualCompactionResponse
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#63 Change the `protoc-gen-go` version to `1.3.2`
  Makefile
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
Labels: ci-passed, dco-passed, lgtm, approved, size/S, kind/improvement

#64 Add the `GetLoadState` api
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#67 add csharp sdk doc
  README.md
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#53 Support upsert
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#70 Update CheckHealthResponse
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL
