Repository milvus-io/milvus-proto, pull requests merged in 2022-09, with the labels that each got.

#36 And query params to query request
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#37 Add ForceDeny and RateLimit error code
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#39 Update to milvus master branch on Step.27
  proto/common.proto
  proto/milvus.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#41 Fix a mistake of pr39
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/M
