Repository milvus-io/milvus-proto, pull requests merged in 2022-06, with the labels that each got.

#24 Update for role access api
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, do-not-merge/missing-related-issue, size/L

#25 Update Proto file
  proto/milvus.proto
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/XS

#26 Minor change for ShowCollection
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, do-not-merge/missing-related-issue, size/XS
