Repository milvus-io/milvus-proto, pull requests merged in 2023-03, with the labels that each got.

#112 Add a NotFoundTSafer error code
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#113 Add msg.proto
  go-api/msgpb/msg.pb.go
  proto/msg.proto
  scripts/proto_gen_go.sh
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#114 Add DataNodeTtMsg to msg.proto
  go-api/commonpb/common.pb.go
  go-api/msgpb/msg.pb.go
  proto/common.proto
  proto/msg.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#119 Add DescribeAlias and ListAliases interface
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#117 Add feder proto
  go-api/commonpb/common.pb.go
  go-api/federpb/feder.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/feder.proto
  proto/milvus.proto
  scripts/proto_gen_go.sh
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#121 Add collection_name in ListAliases request
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#122 Add FlushAll Api
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#124 Add FlushAll api[cherry-pick#122]
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL
