Repository milvus-io/milvus-proto, pull requests merged in 2023-02, with the labels that each got.

#102 remove descriptor.proto
  proto/google/protobuf/descriptor.proto
Labels: ci-passed, dco-passed, approved, do-not-merge/missing-related-issue, size/XL

#103 support rg api rbac
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#104 [Cherry-Pick]Add RenameCollection API
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#105 Add the rbac for the GetLoadingProgress and GetLoadState
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#106 Add the rbac for the GetLoadingProgress and GetLoadState
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#108 Add the `NotReadyServe` error code
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#109 Add the `NotReadyServe` error code
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#107 [cherry-pick]support rg api rbac
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#110 Add the `CoordActivating` error code
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#111 Add the `CoordActivating` error code
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L
