Repository milvus-io/milvus-proto, pull requests merged in 2023-06, with the labels that each got.

#170 [Cherry Pick]Support database API
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, do-not-merge/missing-related-issue, size/XXL

#171 Format 2.2 go module format
  go-api/commonpb/common.pb.go
  go-api/go.mod
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  go.mod
  proto/common.proto
  proto/milvus.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#172 Add v2 pkg path in proto_gen_go.sh
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  scripts/proto_gen_go.sh
Labels: ci-passed, dco-passed, lgtm, approved, size/S, kind/improvement

#173 Add RBAC for FlushAll
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#176 Add error code for streaming rpc
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#177 Cancel ErrorCode RpcStreamContinue
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L
