Repository milvus-io/milvus-proto, pull requests merged in 2023-07, with the labels that each got.

#178 Modify SearchRequest for the SearchByPks use case (to be added)
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#180 Add AllocTimestamp api for Milvus
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#181 Add AllocTimestamp api for Milvus
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#182 add target db parameter into RenameCollectionRequest
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, do-not-merge/missing-related-issue, kind/improvement, size/XL

#183 Change C# namespace to Milvus.Client
  proto/common.proto
  proto/milvus.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#185 [cherry-pick] Change C# namespace to Milvus.Client (#183)
  proto/common.proto
  proto/milvus.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, do-not-merge/missing-related-issue, size/XS
