Repository milvus-io/milvus-proto, pull requests merged in 2023-09, with the labels that each got.

#189 Enhance FlushAll/GetFlushAllState API
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#190 Add flush_ts in GetFlushStateRequest
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#191 Update FlushAll/GetFlushAllState API
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#192 Add collectionName and DBName in GetFlushStateRequest
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#193 Revert deprecat segmentIDs in GetFlushState
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#194 Add the replicate msg api
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/milvus.proto
Labels: kind/improvement
