Repository milvus-io/milvus-proto, pull requests merged in 2023-08, with the labels that each got.

#187 Update the drop index api comment
  go-api/go.sum
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#186 Add float16 vector
  go-api/commonpb/common.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#188 Add new db name for rename collection req
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, do-not-merge/missing-related-issue, size/XL
