Repository milvus-io/milvus-proto, pull requests merged in 2023-04, with the labels that each got.

#126 Refresh progress
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#127 Add array json
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#129 Add element_type for array type
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#130 Support Default Value
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#132 Adjust default value field
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#131 Add GetIndexStatistics interface
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#133 Add database API
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#134 Add the `DbName` param for the rabc grant api
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#135 Fix DropDatabse API
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#136 Add db name to some request
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL
