Repository milvus-io/milvus-proto, pull requests merged in 2023-10, with the labels that each got.

#198 Add properties
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#204 Add VerifyAPIKey method for the hook interface
  go-api/hook/hook.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#205 Update the cdc proto with ts
  go-api/commonpb/common.pb.go
  go-api/hook/hook.go
  proto/common.proto
Labels: size/L

#207 Use the Load privilege when getting the load state
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#202 Add deprecated label for protos
  cmake/protobuf/CMakeLists.txt
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/milvus.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL
