Repository milvus-io/milvus-proto, pull requests merged in 2023-01, with the labels that each got.

#73 [cherry-pick]:built-in protoc and update protoc-gen-go
  Makefile
  cmake/CMakeLists.txt
  cmake/protobuf/CMakeLists.txt
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  scripts/check_protoc_version.sh
  scripts/core_build.sh
  scripts/proto_gen_go.sh
Labels: ci-passed, dco-passed, lgtm, approved, size/M, kind/improvement

#74 cherry-pick: Add the `stopping` node state code
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#75 [cherry-pick]: Add the `GetLoadState` api
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#77 Add error codes for forceDeny and failed load
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#80 [cherry-pick] Update CheckHealthResponse
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#79 [cherry-pick ]Add error codes for forceDeny and failed load
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#72 resource group api
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#83 Revert resource group api
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#84 Support resource group
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#87 fix type error
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#88 Add RenameCollection API
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#91 Add refresh mode for LoadCollection/LoadPartitions
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#92 [Cherry-Pick] Add refresh mode for LoadCollection/LoadPartitions (#91)
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#93 adjust resource group api
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#95 fix ci
  .github/mergify.yml
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#98 Add ci fot branch 2.2
  .github/mergify.yml
Labels: ci-passed, dco-passed, size/S, kind/improvement

#99 Add ut for branch 2.2
  .github/workflows/check.yaml
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/XS

#100 Add ut for branch 2.2
  .github/workflows/check.yaml
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/XS

#101 resource group api
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL
