Repository milvus-io/milvus-proto, pull requests merged in 2023-12, with the labels that each got.

#214 Kdxf dev
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: lgtm, approved, size/XXL

#216 add groupby value field(#215)
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#219 feat: support control index mmap
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#213 partition related apis require corresponding permissions
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#226 update getflushState
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: size/XL

#225 update getflushState
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: size/XL

#227 Define clustering info
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/milvus.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#231 [Cherry-pick] support delete choose consistency level
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#233 Rename searchV2 to HybridSearch
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#235 Add is_clustering_key in fieldschema
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L
