Repository milvus-io/milvus-proto, pull requests merged in 2024-11, with the labels that each got.

#328 enhance: Enable prefer node lables in resource group
  go-api/rgpb/rg.pb.go
  proto/rg.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#335 enhance: Change OpenAI func to textEmb func
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#334 enhance: enable create segment for streaming
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#336 enhance: enable create segment for streaming
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#337 enhance: AlterIndex support delete property
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#285 enhance: [2.4] Make proto check action works for all release branches (#282)
  .github/workflows/check.yaml
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#340 enhance: altercollection support delete property and add new api altercollectionfiled
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#341 Update the template expression proto to improve transmission efficiency
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#342 [2.4]Update the template expression proto to improve transmission efficiency
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#343 enhance: add altercollectionfield grpc interface
  go-api/milvuspb/milvus.pb.go
  go-api/milvuspb/milvus_grpc.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#330 enhance: RBAC custom privilege group
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/milvuspb/milvus_grpc.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#345 enhance: [2.4] RBAC custom privilege group
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/milvuspb/milvus_grpc.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#344 enhance: add search iterator v2 info
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#346 add db id in ListDatabasesResponse
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#347 enhance: Enable prefer node lables in resource group (#328)
  go-api/rgpb/rg.pb.go
  proto/rg.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#348 enhance: RBAC built in privilege groups
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#349 RBAC built in privilege groups
  go-api/commonpb/common.pb.go
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#351 enhance: grant v2 enhancement
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#354 enhance: RBAC operate privilege V2
  go-api/milvuspb/milvus.pb.go
  go-api/milvuspb/milvus_grpc.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#352 enhance: [2.4] RBAC built in privilege groups
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#355 enhance: [2.4] RBAC operate privilege V2
  go-api/milvuspb/milvus.pb.go
  go-api/milvuspb/milvus_grpc.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#357 Support recalls field in SearchResultData
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#358 Support recalls field in SearchResultData
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#360 add replicate end msg
  go-api/commonpb/common.pb.go
  go-api/msgpb/msg.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/msg.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#361 [2.4]: add replicate end message
  go-api/commonpb/common.pb.go
  go-api/msgpb/msg.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/msg.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#362 [2.5]: add replicate end msg
  go-api/commonpb/common.pb.go
  go-api/msgpb/msg.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/msg.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#364 fix: Some privileges can't be grant to user
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, size/XXL

#367 enhance: Add database param to manual compact api
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, size/XXL

#368 enhancement: enhancement alterindex and aliterIndexField
  go-api/milvuspb/milvus.pb.go
  go-api/milvuspb/milvus_grpc.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL
