Repository milvus-io/milvus-proto, pull requests merged in 2024-01, with the labels that each got.

#236 feat: Add privilege definition for alias interfaces
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#238 feat: Add privilege definition for alias interfaces
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: lgtm, approved, size/XXL

#232 Add proto for sparse float vector
  go-api/commonpb/common.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL
