Repository milvus-io/milvus-proto, pull requests merged in 2024-02, with the labels that each got.

#242 Add all search cnt param and report interface
  go-api/go.sum
  go-api/hook/hook.go
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#243 enhance: resource group declarative api
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/rgpb/rg.pb.go
  proto/common.proto
  proto/milvus.proto
  proto/rg.proto
  scripts/proto_gen_go.sh
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#245 Add properties to CollectionSchema
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, do-not-merge/missing-related-issue, size/L

#246 use plain byte array to represent a single sparse row
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L
