Repository milvus-io/milvus-proto, pull requests merged in 2024-09, with the labels that each got.

#317 feat: Support Creat BM25 Function
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#321 feat: Add describe for function schema and add is_function_output for FieldSchema
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#322 Add sorted flag for segmentInfo
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#324 enhance: Add segment id hint in DeleteRequest
  go-api/msgpb/msg.pb.go
  proto/msg.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#326 add sessionTs(#325)
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL
