Repository milvus-io/milvus-proto, pull requests merged in 2024-03, with the labels that each got.

#247 Add majorCompaction field in ManualCompactionRequest
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#249 update comment of PlaceholderValue::values
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/S, do-not-merge/missing-related-issue

#250 Add the return value for the hook report interface
  go-api/hook/hook.go
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#252 enhance: add privilege for AlterAlias
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#254 enhance: add privilege for AlterAlias (#252)
  proto/milvus.proto
Labels: lgtm, approved, size/XS

#257 feat: Add authentication placeholders for ImportV2
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#259 add distances in SearchResultData
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#260 add distances in SearchResultData (#259)
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: lgtm, approved, size/L

#261 fix: use underscore for field name, "from" is keyword in python
  go-api/commonpb/common.pb.go
  go-api/rgpb/rg.pb.go
  proto/common.proto
  proto/rg.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#263 enhance: Make mergify rules work fro 2.x branches
  .github/mergify.yml
Labels: ci-passed, dco-passed, lgtm, approved, size/S, kind/improvement

#264 enhancement: enable 2.4 pipeline
  .github/mergify.yml
  .github/workflows/check.yaml
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#262 fix: use underscore for field name, "from" is keyword in python
  go-api/commonpb/common.pb.go
  go-api/rgpb/rg.pb.go
  proto/common.proto
  proto/rg.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#265 remove float16/bfloat16
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/schema.proto
Labels: dco-passed, lgtm, approved, size/XXL
