Repository milvus-io/milvus-proto, pull requests merged in 2024-04, with the labels that each got.

#267 enhance: support null
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#269 Add the 'db id' field for the DescribeCollectionResponse message
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#270 enhance: [2.4] add the 'db id' field for the DescribeCollectionResponse
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#273 enhance: remove the show collections and list databases privilege
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#274 enhance: [2.4] remove the show collections and list databases privilege
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#268 Add channelCPs in FlushResponse
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#276 enhance: Add AlterDatabase proto
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#278 add generated code for alter database
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#280 enhance: Add AlterDatabase proto (#276)
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#284 Add channelCPs in FlushResponse (#268)
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#283 add proto for DescribeDatabase
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#282 enhance: Make proto check action works for all release branches
  .github/workflows/check.yaml
Labels: ci-passed, dco-passed, lgtm, approved, size/XS
