Repository milvus-io/milvus-proto, pull requests merged in 2024-12, with the labels that each got.

#369 support push info to hook
  go-api/hook/hook.go
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#366 fix: Some privileges can't be grant to user (#364)
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, size/XXL

#372 Enhancement: Add the AlterCollectionField type to MsgType
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#373 Enhancement: Add the AlterCollectionField type to MsgType
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#376 enhance: add pb for query iterator
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#378 enhance: add query cursor for query iterator(#377)
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#380 enhance: alterdatabase support delete property
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#381 Enhancement: Add the AlterCollectionField type to MsgType
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#383 enhance: [2.4]alterdatabase support delete property
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#384 enhance: [2.5] Cherry-pick proto change from master
  go-api/hook/hook.go
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#385 Add new data type Int8Vector
  go-api/commonpb/common.pb.go
  go-api/schemapb/schema.pb.go
  proto/common.proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#386 [Cherry-pick]Support push info to hook (#369)
  go-api/hook/hook.go
Labels: ci-passed, dco-passed, lgtm, approved, size/S
