Repository milvus-io/milvus-proto, pull requests merged in 2024-08, with the labels that each got.

#305 enhance: [2.4] Add Field Partial load params in load requests (#304)
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#306 enhance: Add BackupRBAC/RestoreRBAC API to enable rbac backup
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/milvuspb/milvus_grpc.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, size/XXL

#308 enhance: Enable ReadOnly/ReadWrite/Admin Privilege Group to simplify RBAC grant progress
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, size/M

#309 enhance: Add BackupRBAC/RestoreRBAC API to enable rbac backup (#306)
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, size/XXL

#310 enhance: Enable ReadOnly/ReadWrite/Admin Privilege Group to simplify RBAC grant progress (#308)
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, size/L

#311 enhance: add new message type for flusher in streaming service
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, size/L

#312 enhance: Update protobuf-go to protobuf-go v2 (#294)
  Makefile
  go-api/commonpb/common.pb.go
  go-api/federpb/feder.pb.go
  go-api/go.mod
  go-api/go.sum
  go-api/milvuspb/milvus.pb.go
  go-api/milvuspb/milvus_grpc.pb.go
  go-api/msgpb/msg.pb.go
  go-api/rgpb/rg.pb.go
  go-api/schemapb/schema.pb.go
  scripts/proto_gen_go.sh
Labels: ci-passed, dco-passed, lgtm, size/XXL

#313 use the GetLoadState privilege in the GetLoadState and GetLoadingProgress Request
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#314 [2.4]: use the GetLoadState privilege in the GetLoadState and GetLoadingProgress Request
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#315 add `force_drop` param for the drop role request
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#316 [2.4]: add `force_drop` param for the drop role request
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/M
