Repository milvus-io/milvus-proto, pull requests merged in 2025-09, with the labels that each got.

#471 feat: Add CDC API and related definitions
  go-api/commonpb/common.pb.go
  go-api/milvuspb/milvus.pb.go
  go-api/milvuspb/milvus_grpc.pb.go
  proto/common.proto
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#477 enhance: Sync milvus maintainer
  OWNERS
Labels: ci-passed, dco-passed, lgtm, approved, do-not-merge/missing-related-issue, size/XS

#474 feat: Add namespace field in InsertRequest to support multi-tenant
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#479 enhance: add namespace field to search/query request
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#485 feat: add Struct proto
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#487 feat: add l0 compaction option for mannual compaction(#486)
  go-api/milvuspb/milvus.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL
