Repository milvus-io/milvus-proto, pull requests merged in 2025-02, with the labels that each got.

#406 Support run analyzer
  go-api/milvuspb/milvus.pb.go
  go-api/milvuspb/milvus_grpc.pb.go
  proto/milvus.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#408 feat: add text data type
  go-api/schemapb/schema.pb.go
  proto/schema.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#409 feat: add import msg
  .gitignore
  go-api/commonpb/common.pb.go
  go-api/msgpb/msg.pb.go
  proto/common.proto
  proto/msg.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#410 feat: [2.5] add import msg
  .gitignore
  go-api/commonpb/common.pb.go
  go-api/msgpb/msg.pb.go
  proto/common.proto
  proto/msg.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#411 feature: Add CipherPlugin Interfaces
  go-api/hook/hook.go
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#414 fix: add OperatePrivilegeV2 enum to MsgType
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#416 fix: [2.5] add OperatePrivilegeV2 enum to MsgType
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#415 fix: [2.4] add OperatePrivilegeV2 enum to MsgType
  go-api/commonpb/common.pb.go
  proto/common.proto
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L
